### ISSUE TITLE
It seems not to work on Plasma6

### ISSUE THREAD

**Issue by GuMengSama** [arithefirst/BreezeEnhancedCatppuccin#1]
CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt6::Gui" does
not agree with the value of QT_MAJOR_VERSION already determined
for "breezeenhanced".

**Comment by AriTheFirst** [comment]
I haven't updated this for plasma6 and do not have plans to, I mostly made this for myself and I use 5.27. I recommend just going to the repo this was forked from and modifying the code to change the colors.

**Comment by arithefirst** [comment]
Currently working on updating this to work in KDE 6

**Comment by arithefirst** [comment]
Support has been added for KDE Plasma 6, use the installer in the README to install.
